#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Error: CIDR range required"
    echo "Usage: $0 <CIDR>"
    echo "Example: $0 192.168.0.0/24"
    exit 1
fi

echo $1 | tlsx -silent -san -cn -resp-only | sort -u | dnsx -silent | httpx -sc -probe -title -tech-detect -silent
